Dev
superles/yapgofermart pull request #2
Opened 2023-11-23 09:04 UTC by superles

2023-11-24 08:39 UTC, gonozov0 requested changes
Отличное начало 👍
Оставил пару комментариев по улучшению кода.

Также договорились на встрече про изменения:
- вынеса бизнес логики на строне бд в код
- изменения логики горутин при обновлении заказа
- написания интерфейса и мок реализиций для клиента и стореджа
- написание интеграционных тестов с использованием мок реализаций

2023-11-24 08:39 UTC, gonozov0 commented on api/api.yml
Респект, ты это сам описывал или сгенерировал из кода?

2023-11-24 08:39 UTC, gonozov0 commented on internal/config/config.go
> +		return "" // Возвращаем пустую строку в случае ошибки парсинга
а почему не обернутую ошибку? неявная логика

2023-11-24 08:39 UTC, gonozov0 commented on internal/errors/storage.go
Вместо отдельного глобального пакета с ошибками, я бы лучше добавил errors.go в пакет storage, с withdrawal аналогично

2023-11-24 08:39 UTC, gonozov0 commented on internal/utils/hasher/hasher.go
> +	// Создаем hmac sha256 с ключом
Тут вроде и так это понятно по коду, лучше описать комментарий, как doc string к самой функции

2023-11-24 08:39 UTC, gonozov0 commented on internal/utils/hasher/hasher.go
> +	// Создаем hmac sha256 с ключом
аналогично

2023-11-24 08:39 UTC, gonozov0 commented on internal/withdrawal/withdrawal.go
видимо лишний пакет, который забыл удалить

2023-11-27 10:12 UTC, superles commented on api/api.yml
Я это сгенерировал из postman коллекции. Плюс немного обработал

2023-11-27 10:13 UTC, superles commented on internal/withdrawal/withdrawal.go
да. это лишний пакет из старого проекта

2023-11-29 08:56 UTC, gonozov0 requested changes
Превосходная работа, структура супер понятная, код легко читать и ревьюить 👍

Осталась последняя из важных вещей, что я требую в финальном проекте - это написание интеграционных или end-to-end (e2e) тестов.
Под интеграционными тестами я подразумеваю тест на бизнес логику приложения (вызов ручек + проверка результатов), но без походов во внешний мир. То есть для Storager и клиента к внешней системе заказов должны быть определены интерфейсы и реализована их Mock/InMemory имплементация, которая будет использоваться в этих тестах.
Под e2e - тоже тесты на бизнес логику, но в этот раз уже с походами во все внешние сервисы, то есть для их работы нужно будет отдельно поднять локально базу данных и систему заказов, указать верные адреса, порты и т.д.

В рамках этого проекта мне важно увидеть 1 интеграционный или e2e тест на всю бизнес логику заказа, то есть:
1. дергается ручка создания заказа
2. в фоне происходит поход во внешнюю систему и обновляется статус заказа на Processed
3. в фоне происходит начисление баллов на счет пользователя
4. в тесте происходит проверка, что заказ обновлен и увеличен баланс пользователя

С учетом того, что ты уже отлично реализовал MemStorage, логичнее и проще будет написать интеграционный тест, но выбор за тобой

2023-11-29 08:56 UTC, gonozov0 commented on internal/accrual/client.go
> +type ClientHTTP struct {
Высший пилотаж будет сделать эту структуру неэкспортирумой и реализовать для нее экспортируемый конструктор, который будет возвращать интерфейс Client

2023-11-29 10:37 UTC, superles commented on internal/config/config.go
> +		return "" // Возвращаем пустую строку в случае ошибки парсинга
сделал

2023-11-29 13:27 UTC, superles commented on internal/accrual/client.go
> +type ClientHTTP struct {
добавил end-to-end с моками. сложновато у меня как-то вышло. нужно видимо как-то проще, но так сразу ничего в голову не пришло

2023-11-29 13:27 UTC, superles commented on internal/accrual/client.go
> +type ClientHTTP struct {
буду рад если натолкнешь на мысль и дашь пример как тестировать end to end rest api с реализацией авторизации разными пользователями итд

2023-11-30 08:57 UTC, gonozov0 requested changes
Отписал комментарии по коду

2023-11-30 08:57 UTC, gonozov0 commented on cmd/gophermart/main_test.go
> +	}
Это очень сложно читать, лучше не обобщай логику на общие аргументы, функцию проверки, сделай сделай для каждого теста отдельный тест в suite. В данном случае лучше дублировать код, чем делать его нечитаемым

2023-11-30 08:57 UTC, gonozov0 commented on cmd/gophermart/main_test.go
> +	}
как пример
https://github.com/gonozov0/go-musthave-devops/blob/main/internal/server/repository/postgres/postgres_test.go

2023-11-30 08:57 UTC, gonozov0 commented on cmd/gophermart/main_test.go
> +}
Ты вроде создал client_mock рядом с реальной реализацией, почему ее не стал использовать?

2023-11-30 10:39 UTC, superles commented on cmd/gophermart/main_test.go
> +}
client_mock создан для последовательной отдачи нужных ответов, учитывая ошибки итд. Те хорош для unit тестирования используя все кейсы. А для e2e вроде как и не нужен, потому что придется в каждый кейс свой клиент. И я решил упростить. Плохая практика?

2023-11-30 14:39 UTC, superles commented on cmd/gophermart/main_test.go
> +	}
Удобно. Сделал

2023-11-30 14:40 UTC, superles commented on cmd/gophermart/main_test.go
> +	}
Получилось вроде бы неплохо. Сделал

2023-11-30 14:40 UTC, superles commented on cmd/gophermart/main_test.go
> +	}
Сделал

2023-12-01 08:29 UTC, merged